services:

  llama-server:
    build:
      context: .
      dockerfile: Dockerfile.llamacpp.server
      args:
        LLAMACPP_IMAGE: ${LLAMACPP_IMAGE}
    container_name: llama-server
    # restart: unless-stopped
    ports:
      - "${LLAMACPP_PORT}:8080"
      - "${MODELCTL_API_PORT:-8000}:8000"
    volumes:
      - ./registry:/opt/model-manager/registry
      - ./storage:/models
    environment:
      - MODELCTL_API_REGISTRY_DIR=/opt/model-manager/registry
      - MODELCTL_API_STORAGE_DIR=/models
      - MODELCTL_API_PORT=${MODELCTL_API_PORT:-8000}
      - HF_TOKEN=${HF_TOKEN:-}
    command: >
      --host 0.0.0.0 --port 8080
