services:

  llama-server:
    build:
      context: .
      dockerfile: Dockerfile.llamacpp.server
      args:
        LLAMACPP_IMAGE: ${LLAMACPP_IMAGE}
    container_name: llama-server
    # restart: unless-stopped
    ports:
      - "${LLAMACPP_PORT}:8080"
      - "${MODELCTL_API_PORT:-8000}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/LLMGateway-Models/registry:${HOME}/LLMGateway-Models/registry
      - ${HOME}/LLMGateway-Models:${HOME}/LLMGateway-Models
    environment:
      - MODELCTL_API_REGISTRY_DIR=${HOME}/LLMGateway-Models/registry
      - MODELCTL_API_STORAGE_DIR=${HOME}/LLMGateway-Models/storage
      - MODELCTL_API_PORT=${MODELCTL_API_PORT:-8000}
      - HF_TOKEN=${HF_TOKEN:-}
    command: >
      --host 0.0.0.0 --port 8080
